# Generated by Django 4.2.16 on 2026-05-25 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('record_created', 'Record Created'), ('record_edited', 'Record Edited'), ('record_approved', 'Record Approved'), ('record_flagged', 'Record Flagged'), ('record_rejected', 'Record Rejected'), ('bulk_approved', 'Bulk Approved'), ('bulk_flagged', 'Bulk Flagged'), ('run_started', 'Ingestion Run Started'), ('run_completed', 'Ingestion Run Completed'), ('run_failed', 'Ingestion Run Failed')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emission_record_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ingestion_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
