# Generated by Django 4.2.16 on 2026-05-25 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCode',
            fields=[
                ('iata', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=18)),
                ('co2_per_unit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('ch4_per_unit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('n2o_per_unit', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_source', models.CharField(choices=[('DEFRA_2024', 'UK DEFRA 2024'), ('EPA_2023', 'US EPA eGRID 2023'), ('IPCC_AR6', 'IPCC AR6'), ('GHG_PROTOCOL', 'GHG Protocol')], max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct emissions'), (2, 'Scope 2 — Purchased electricity'), (3, 'Scope 3 — Value chain')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel — Flights'), ('business_travel_hotel', 'Business Travel — Hotels'), ('business_travel_ground', 'Business Travel — Ground'), ('procurement', 'Purchased Goods & Services'), ('waste', 'Waste')], max_length=40)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_normalized', models.CharField(max_length=30)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=100)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('co2_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ch4_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('n2o_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flags', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=30, unique=True)),
                ('to_unit', models.CharField(max_length=30)),
                ('multiplier', models.DecimalField(decimal_places=10, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
